- backend/README.md
- backend/app/api/auth/v1/router.py
- backend/app/common/auth/jwt.py
- backend/app/modules/auth/handlers.py
- backend/app/modules/auth/repository.py
- backend/app/modules/auth/schemas.py
[질문사항]
1. 인증/인가 부분은 최대한 간단히 하기 위해, jwt access_token과 refresh_token 모두 client에게 전달하였습니다. 다만 지금 생각해보니, 세션과 큰 차이점을 못 느끼고 있습니다. 어차피 refresh_token을 저장하면 session과 동일한 stateful 상태입니다. 그럼에도 불구하고 jwt시 장점이 있을가요?
> feat : new access token issue

- backend/README.md
- backend/app/api/auth/v1/router.py
- backend/app/common/auth/jwt.py
- backend/app/dependencies/database.py
- backend/app/modules/auth/handlers.py
- backend/app/modules/auth/models.py
- backend/app/modules/auth/repository.py
- backend/app/service/singleton.py
- backend/database/config.py
- backend/main.py
- backend/poetry.lock
- backend/pyproject.toml
- postrgresql > mysql으로 바꿨습니다
- 코드 리뷰 참조 후 수정하였습니다.
> feat : change to mysql

- backend/README.md
- backend/app/api/auth/v1/router.py
- backend/app/modules/auth/handlers.py
- backend/app/modules/auth/schemas.py
- backend/database/config.py
- backend/main.py
- backend/poetry.lock
- backend/pyproject.toml
- backend/test/app/api/auth/v1/test_router.py
- backend/test/app/common/auth/test_jwt.py
- backend/test/app/modules/auth/test_handlers.py
- backend/test/app/modules/auth/test_repository.py
- backend/test/conftest.py
[변경 사항]
- bussiness logic unit test 적용
- conftest.py 추가
> feat : auth unit test

- backend/data/finance_reader.py
- backend/data/interface.py
- backend/data/sources/auth.py
- backend/data/sources/stock_info.py
- backend/mypy.ini
- backend/poetry.lock
- backend/pyproject.toml
[내용]
한국 투자 증권 api > websocket 다중 연결. 주식 장이 열리는 시간에 재확인 필요
> feat: 한국투자증권 api 초기 설정

- backend/app/common/auth/jwt.py
- backend/app/modules/auth/repository.py
- backend/data/sources/stock_info.py
- backend/makefile
- backend/test/app/api/auth/v1/test_router.py
- backend/test/app/common/auth/test_jwt.py
- backend/test/app/modules/auth/test_repository.py
> fix: magic number remove, add makefile

- README.md
[설명]
README 수정 > fastapi docker로 실행 방법 소개
> GENTLEGROW-10 docs: Change README

- backend/Dockerfile
- backend/app/api/asset/v1/router.py
- backend/app/api/chart/v1/router.py
- backend/app/data/polygon/realtime_market_index.py
- backend/app/data/polygon/source/constant.py
- backend/app/data/polygon/source/service.py
- backend/app/data/yahoo/dividend.py
- backend/app/module/asset/constant.py
- backend/app/module/asset/model.py
- backend/app/module/asset/redis_repository.py
- backend/app/module/asset/repository/dividend_repository.py
- backend/app/module/asset/repository/stock_daily_repository.py
- backend/app/module/asset/schema.py
- backend/app/module/asset/service.py
- backend/app/module/chart/enum.py
- backend/app/module/chart/redis_repository.py
- backend/app/module/chart/schema.py
- backend/docker/Dockerfile.market_index_historical
- backend/test/app/api/chart/v1/test_router.py
- backend/test/app/module/asset/test_asset_service.py
- backend/test/conftest.py
> [GROW-71] 자산관리 api 내에 비즈니스 로직 수정

- backend/app/api/chart/v1/router.py
- backend/app/data/naver/korea_market_index_realtime.py
- backend/app/data/naver/world_market_index_realtime.py
- backend/app/module/asset/constant.py
- backend/app/module/asset/enum.py
- backend/docker/Dockerfile.realtime_korea_market_index
- backend/docker/Dockerfile.realtime_world_market_index
- backend/etc/scripts/start_realtime_korea_market_index.sh
- backend/etc/scripts/start_realtime_world_market_index.sh
> [GROW-71] 시장 지수 수집 shell script 추가

- backend/Dockerfile
- backend/app/api/asset/v1/router.py
- backend/app/api/chart/v1/router.py
- backend/app/data/naver/world_market_index_realtime.py
- backend/app/data/yahoo/exchange_rate.py
- backend/app/module/asset/service.py
- backend/app/module/asset/services/asset_stock_service.py
- backend/app/module/asset/services/dividend_service.py
- backend/app/module/asset/services/exchange_rate_service.py
- backend/app/module/asset/services/stock_service.py
- backend/app/module/chart/enum.py
- backend/app/module/chart/schema.py
- backend/app/module/chart/service/composition_service.py
- backend/docker/Dockerfile.realtime_world_market_index
- backend/index.html
> [GROW-71] 종목 구성 api 개발 

- backend/app/api/chart/v1/router.py
- backend/app/module/asset/constant.py
- backend/app/module/asset/enum.py
- backend/app/module/chart/schema.py
> [GROW-71] 미국 시장 지수 api 한국어 추가

- backend/app/api/chart/v1/router.py
- backend/app/data/naver/world_market_index_realtime.py
- backend/app/module/asset/constant.py
- backend/app/module/asset/redis_repository.py
- backend/app/module/asset/service.py
- backend/app/module/chart/redis_repository.py
- backend/app/module/chart/schema.py
- backend/app/module/chart/service/performance_analysis_service.py
- backend/docker/Dockerfile.realtime_world_market_index
> [GROW-71] selenium docker 실행

- backend/app/data/yahoo/stock_historical.py
- backend/app/data/yahoo/stock_historical_all.py
- backend/app/module/asset/model.py
- backend/app/module/asset/services/asset_stock_service.py
- yfinance 401 데이터 수집 에러 처리 -> 다른 yfinance api로 대체
> [GROW-73] yfinance 401 데이터 수집 에러 처리 -> 다른 yfinance api로 대체

- backend/app/api/asset/v1/router.py
- backend/app/api/chart/v1/router.py
- backend/app/data/yahoo/dividend.py
- backend/app/data/yahoo/realtime_stock/realtime_stock_collect.py
- backend/app/data/yahoo/realtime_stock/realtime_stock_run.py
- backend/app/module/asset/model.py
- backend/app/module/asset/repository/dividend_repository.py
- backend/app/module/asset/repository/stock_minutely_repository.py
- backend/app/module/chart/schema.py
- backend/app/module/chart/service/estimate_dividend_service.py
- backend/docker/Dockerfile.realtime_stock
- backend/etc/scripts/realtime_stock.sh
- backend/makefile
> [GROW-73] 배당 데이터 수집 변경 

- backend/app/api/chart/v1/router.py
- backend/app/module/asset/services/dividend_service.py
- backend/app/module/chart/enum.py
- backend/app/module/chart/schema.py
- backend/app/module/chart/service/performance_analysis_service.py
> [GROW-73] 투자 성과 분석 반환 타입 변경

- backend/app/api/chart/v1/router.py
- backend/app/data/investing/rich_portfolio.py
- backend/app/module/chart/schema.py
- backend/app/module/chart/service/performance_analysis_service.py
> [GROW-73] 투자성관분석 반환 형태 변경

- backend/app/api/chart/v1/router.py
- backend/app/data/investing/rich_portfolio.py
- backend/app/data/investing/sources/enum.py
- backend/app/module/asset/repository/asset_repository.py
- backend/app/module/auth/repository.py
- backend/app/module/chart/schema.py
> [GROW-73] 예상 배당액 api 반환 포맷 변경

- backend/app/api/chart/v1/router.py
- backend/app/data/investing/rich_portfolio.py
- backend/app/module/asset/services/stock_service.py
- backend/app/module/chart/constant.py
- backend/app/module/chart/redis_repository.py
- backend/app/module/chart/schema.py
> [GROW-73] 부자 포트폴리오 api 개발

- backend/app/api/chart/v1/router.py
- backend/app/data/investing/rich_portfolio.py
- backend/app/module/chart/redis_repository.py
- backend/app/module/chart/schema.py
- backend/docker/Dockerfile.rich_portfolio
> [GROW-73] 부자 포트폴리오 수집 도커 파일 수정

- backend/app/api/chart/v1/router.py
- backend/app/module/asset/schema.py
- backend/app/module/chart/redis_repository.py
- backend/app/module/chart/service/rich_portfolio_service.py
- backend/test/app/module/chart/service/conftest.py
- backend/test/app/module/chart/service/test_rich_portfolio_service.py
- backend/test/fixtures/chart/test_asset_fixture.py
> [GROW-73] 부자들의 포트폴리오 api 개발

- backend/app/api/chart/v1/router.py
- backend/app/module/chart/redis_repository.py
- backend/app/module/chart/service/rich_portfolio_service.py
- backend/docker/Dockerfile.create_table
- backend/docker/Dockerfile.dividend
- backend/docker/Dockerfile.exchange_rate
- backend/docker/Dockerfile.index
- backend/docker/Dockerfile.index_all
- backend/docker/Dockerfile.insert_basic_data
- backend/docker/Dockerfile.realtime_index_korea
- backend/docker/Dockerfile.realtime_stock
- backend/docker/Dockerfile.realtime_stock_korea
- backend/docker/Dockerfile.realtime_stock_world
- backend/docker/Dockerfile.stock
- backend/docker/Dockerfile.stock_all
- backend/docker/Dockerfile.stock_code
- backend/docker/Dockerfile.tip
- backend/test/app/module/chart/service/conftest.py
- backend/test/app/module/chart/service/test_rich_portfolio_service.py
- backend/test/fixtures/chart/test_asset_fixture.py
> [GROW-73] dockerfile python 일반 base 사용

- backend/app/api/chart/v1/router.py
- backend/app/data/initial/insert_basic_data.py
- backend/app/module/asset/constant.py
- backend/app/module/asset/schema.py
- backend/app/module/asset/services/asset_field_service.py
- backend/app/module/chart/constant.py
- backend/app/module/chart/repository.py
- backend/app/module/chart/schema.py
- backend/app/module/chart/service/indice_service.py
- backend/docker/Dockerfile.realtime_index_world
- backend/docker/Dockerfile.rich_portfolio
- backend/test/app/module/asset/services/conftest.py
- backend/test/app/module/asset/services/test_asset_field_service.py
- backend/test/app/module/asset/services/test_asset_stock_service.py
- backend/test/app/module/asset/test_schema.py
- backend/test/app/module/chart/conftest.py
- backend/test/app/module/chart/service/test_repository.py
- backend/test/fixtures/asset/test_asset_fixture.py
- backend/test/fixtures/chart/test_asset_fixture.py
> [GROW-73] 자산 필드 api 수정

- backend/app/module/asset/services/asset_stock_service.py
> [GROW-73] stockasset 필수 필드 추가

- backend/app/api/chart/v1/router.py
- backend/app/module/asset/services/asset_stock_service.py
- backend/app/module/chart/schema.py
- backend/app/module/chart/service/summary_service.py
- backend/main.py
- backend/poetry.lock
- backend/pyproject.toml
- backend/test/app/module/chart/service/conftest.py
- backend/test/app/module/chart/service/test_summary_service.py
> [GROW-73] summary api 반환 타입 변경

- backend/app/api/chart/v1/router.py
- backend/app/data/initial/insert_basic_data.py
- backend/app/module/asset/services/asset_stock_service.py
- backend/app/module/auth/constant.py
- backend/app/module/auth/repository.py
- backend/app/module/chart/enum.py
- backend/app/module/chart/redis_repository.py
- backend/app/module/chart/schema.py
- backend/app/module/chart/service/performance_analysis_service.py
- backend/app/module/chart/service/summary_service.py
- backend/test/app/module/chart/conftest.py
- backend/test/app/module/chart/service/conftest.py
- backend/test/app/module/chart/service/test_performance_analysis_service.py
- backend/test/app/module/chart/service/test_summary_service.py
- backend/test/app/module/chart/test_schema.py
- backend/test/fixtures/chart/test_asset_fixture.py
> [GROW-73] 투자성관분석 api 반환 포맷 변경

- backend/app/api/chart/v1/router.py
- backend/app/data/initial/insert_basic_data.py
- backend/app/module/chart/redis_repository.py
- backend/app/module/chart/schema.py
- backend/app/module/chart/service/performance_analysis_service.py
- backend/test/app/module/chart/conftest.py
- backend/test/app/module/chart/service/conftest.py
- backend/test/app/module/chart/service/test_performance_analysis_service.py
- backend/test/app/module/chart/test_schema.py
- backend/test/fixtures/chart/test_asset_fixture.py
> [GROW-73] 투자성과분석 데이터 반환 포맷 변경

- backend/README.md
- backend/app/api/chart/v1/router.py
- backend/app/module/asset/constant.py
- backend/app/module/asset/services/dividend_service.py
- backend/app/module/chart/facade/dividend_facade.py
- backend/app/module/chart/schema.py
- backend/app/module/chart/service/performance_analysis_service.py
- backend/test/app/module/asset/services/test_dividend_service.py
- backend/test/app/module/chart/facade/conftest.py
- backend/test/app/module/chart/facade/test_dividend_facade.py
- 예상 배당액 service layer > facade layer 분리 및 테스트 코드 작성
> [GROW-73]  예상 배당액 service layer > facade layer 분리 및 테스트 코드 작성

- backend/app/api/chart/v1/router.py
- backend/app/module/chart/service/performance_analysis_service.py
> [GROW-73] 투자성과분석 포맷 변경

- backend/app/api/chart/v1/router.py
- backend/app/common/util/time.py
- backend/app/module/asset/services/current_index_service.py
- backend/app/module/asset/services/market_index_daily_service.py
- backend/app/module/asset/services/market_index_minutely_service.py
- backend/app/module/chart/enum.py
- backend/app/module/chart/facade/composition_facade.py
- backend/app/module/chart/facade/dividend_facade.py
- backend/app/module/chart/facade/performance_analysis_facade.py
- backend/test/app/api/asset/v1/conftest.py
- backend/test/app/module/asset/conftest.py
- backend/test/app/module/asset/repository/conftest.py
- backend/test/app/module/asset/services/conftest.py
- backend/test/app/module/asset/services/test_current_index_service.py
- backend/test/app/module/asset/services/test_market_index_daily_service.py
- backend/test/app/module/asset/services/test_market_index_minutely_service.py
- backend/test/app/module/chart/conftest.py
- backend/test/app/module/chart/facade/conftest.py
- backend/test/app/module/chart/facade/test_composition_facade.py
- backend/test/app/module/chart/service/conftest.py
- backend/test/fixtures/asset/test_asset_fixture.py
> [GROW-73] 예상 배당액 데이터 없을 때 반환 형태 변경

- backend/app/api/chart/v1/router.py
- backend/app/module/asset/services/market_index_minutely_service.py
- backend/app/module/chart/facade/performance_analysis_facade.py
- backend/app/module/chart/schema.py
- backend/test/app/api/asset/v1/conftest.py
- backend/test/app/module/asset/conftest.py
- backend/test/app/module/asset/repository/conftest.py
- backend/test/app/module/asset/services/conftest.py
- backend/test/app/module/asset/services/test_market_index_minutely_service.py
- backend/test/app/module/chart/conftest.py
- backend/test/app/module/chart/facade/conftest.py
- backend/test/app/module/chart/facade/test_performance_analysis_facade.py
- backend/test/app/module/chart/service/conftest.py
- backend/test/fixtures/asset/test_asset_fixture.py
> [GROW-73] chart api 예외처리 및 반환 포맷 변경

- backend/app/api/chart/v1/router.py
- backend/app/module/chart/schema.py
- backend/test/app/module/chart/test_schema.py
> [GROW-73] 시장 지수, 내 보유 주식 api 반환 포맷 변경

- frontend/src/app/asset-management/layout.tsx
- frontend/src/app/asset-management/overview/page.tsx
- frontend/src/widgets/tab/Tabs.tsx
> GROW-94 feat: 투자 성과, 종목 구성 섹션 반응형 레이아웃 구현

- frontend/src/app/asset-management/overview/page.tsx
- frontend/src/app/globals.css
- frontend/src/app/page.tsx
- frontend/src/features/login/ui/LoginDialog.tsx
- frontend/src/shared/hooks/useMediaQuery.ts
- frontend/src/shared/ui/Tooltip.tsx
- frontend/src/widgets/assets-accumulate-trend/ui/AssetsAccumulateTrend.tsx
- frontend/src/widgets/assets-accumulate-trend/ui/AssetsAccumulateTrendTooltip.tsx
- frontend/src/widgets/header/ui/Header.tsx
- 자산 축적 추이 컴포넌트 개발
- 관련 섹션 반응형 디자인 구현
- useLogin 시그니쳐 수정 => 별로라고 생각하시면 롤백 하겠습니다:)
> GROW-97 feat: 자산 추적 추이 컴포넌트 구현

- frontend/src/widgets/top-10-selected-by-rich-person/ui/Top10SelectedByRichPerson.tsx
- 부자들이 선택한 종목 TOP10 데이터 못 받아 온 경우 UI 분기 처리
> GROW-102 feat:  부자들이 선택한 종목 TOP10 데이터 에러 핸들링

- frontend/public/images/checkbox_check.svg
- frontend/src/shared/index.ts
- frontend/src/shared/ui/CheckBox.tsx
- frontend/src/shared/ui/DatePicker.tsx
- frontend/src/shared/ui/DragAndDropDropdown.tsx
- frontend/src/shared/ui/table/HandleColumDisplayButton.tsx
- frontend/src/shared/ui/table/Table.tsx
- frontend/src/shared/ui/table/TableColumn.tsx
- frontend/src/shared/ui/table/TableHeader.tsx
- frontend/src/stories/CheckBox/CheckBox.stories.tsx
- frontend/src/stories/DatePicker/DatePicker.stories.tsx
- frontend/src/stories/DragAndDropDropdown/DragAndDropDropdown.stories.tsx
- frontend/src/widgets/asset-management-draggable-table/constants/allField.ts
- frontend/src/widgets/asset-management-draggable-table/ui/AssetManegementDraggableTable.tsx
- 드래그 앤 드롭에 사용될 체크박스 컴포넌트 구현
- 드래그 앤 드롭 기능 구현
> GROW-128 feature: 드래그 앤 드롭 컴포넌트 구현

- frontend/src/app/asset-management/sheet/page.tsx
- frontend/src/shared/lib/query-keys.ts
- frontend/src/widgets/asset-management-draggable-table/api/getAssetsStock.ts
- frontend/src/widgets/asset-management-draggable-table/quries/useGetAssetStocks.ts
- frontend/src/widgets/asset-management-draggable-table/types/table.d.ts
- frontend/src/widgets/asset-management-draggable-table/ui/AssetManegementDraggableTable.tsx
- frontend/src/widgets/asset-management-guest-access-guide-button/ui/AssetManagementAccessGuideButton.tsx
- 테이블 컴포넌트 API 연동
- 토큰 없을시 Floating Action Button 노출
> GROW-132 feat: 자신 관리 시트 테이블 API 연동

- frontend/src/shared/ui/NumberInput.tsx
- frontend/src/shared/utils/assert.ts
- frontend/src/shared/utils/number.ts
- frontend/src/stories/NumberInput/NumberInput.stories.tsx
- frontend/tailwind.config.ts
> GROW-111 feature: 테이블 셀 숫자 입력 컴포넌트 개발

- frontend/package.json
- frontend/src/app/asset-management/sheet/page.tsx
- frontend/src/entities/assetManagement/apis/getBrokerAccountList.ts
- frontend/src/entities/assetManagement/apis/getItemNameList.ts
- frontend/src/shared/ui/table/Table.tsx
- frontend/src/shared/ui/table/TableColumn.tsx
- frontend/src/widgets/asset-management-draggable-table/api/getAssetsStock.ts
- frontend/src/widgets/asset-management-draggable-table/quries/useGetAssetStocks.ts
- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementDraggableTable.tsx
- frontend/src/widgets/asset-management-draggable-table/ui/ItemNameCell.tsx
- frontend/src/widgets/index.ts
- frontend/tailwind.config.ts
- frontend/yarn.lock
- 종목명 컴포넌트 UI 구현
- 검색 기능 추가 (Fuse.js 라이브러리 설치)
- 종목명 컴포넌트 API 연동
> GROW-112 feature: 요약 시트 종목 명 드롭다운 컴포넌트 구현

- frontend/src/app/layout.tsx
- frontend/src/shared/ui/Card.tsx
- frontend/src/shared/ui/PortfolioItem.tsx
- frontend/src/shared/ui/PriceDisplay.tsx
- frontend/src/widgets/HomeGuestAccessGuide/ui/HomeGuestAccessGuideButton.tsx
- frontend/src/widgets/Summary/ui/Summary.tsx
- frontend/src/widgets/daily-investment-tip/ui/DailyInvestmentTip.tsx
- frontend/src/widgets/estimate-dividend/ui/EstimateDividendClient.tsx
- frontend/src/widgets/explore-portfolio/ui/ExplorePortfolio.tsx
- frontend/src/widgets/investment-performance-chart/ui/InvestmentPerformanceChartClient.tsx
- frontend/src/widgets/market-index/ui/MarketIndexItem.tsx
- frontend/src/widgets/my-stocks/ui/MyStocks.tsx
- frontend/src/widgets/rich-portfolios/ui/RichPortfolio.tsx
- frontend/src/widgets/stock-composition/ui/StockComposition.tsx
- frontend/src/widgets/top-10-selected-by-rich-person/ui/Top10SelectedByRichPerson.tsx
- 플로팅 버튼 위치 하단 고정
- h3, h2 요소 텍스트컬러 (0a0a0a->gray-100)
- 수익금이 0으로 표시되는 문제 수정
> GROW-140 fix: h2, h3 텍스트 컬러 / 플로팅 버튼 위치 / 수익금 0으로 표시되는 문제 수정

- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementDraggableTable.tsx
> GROW-138 feature: 데이트 피커 컴포넌트 테이블 시트와 연동

- frontend/src/shared/ui/NumberInput.tsx
- frontend/src/shared/utils/number.ts
- frontend/src/stories/NumberInput/NumberInput.stories.tsx
- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementDraggableTable.tsx
> GROW-139 feature: 숫자 입력 컴포넌트 자산 관리 시트와 연동

- frontend/src/app/asset-management/layout.tsx
- frontend/src/app/asset-management/overview/page.tsx
- frontend/src/app/layout.tsx
- frontend/src/shared/ui/NumberInput.tsx
- frontend/src/shared/ui/table/Table.tsx
- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementDraggableTable.tsx
- frontend/src/widgets/footer/ui/Footer.tsx
- frontend/src/widgets/header/ui/Header.tsx
- frontend/src/widgets/index.ts
- Header, Footer 컴포넌트 반응형 레이아웃 로직 수정
- 자산 관리 시트 페이지 반응형 레이아웃 적용
> GROW-115 feature: 자산 관리 시트 페이지 반응형 레이아웃 적용

- frontend/public/images/info2.svg
- frontend/src/shared/ui/DragAndDropDropdown.tsx
- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementDraggableTable.tsx
- 테이블 헤더 및 푸터 UI 개발
- 드래그 앤 드롭 드롭다운 모바일 대응 기능 추가
> GROW-143 feature: 테이블 헤더 및 푸터 UI 개발

- frontend/src/components/ui/resizable.tsx
- frontend/src/shared/hooks/useDragAndDrop.tsx
- frontend/src/shared/ui/table/Table.tsx
- frontend/src/shared/ui/table/TableCell.tsx
- frontend/src/shared/ui/table/TableColumn.tsx
- frontend/src/shared/ui/table/TableHeader.tsx
- frontend/src/widgets/asset-management-draggable-table/quries/useGetAssetStocks.ts
- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementDraggableTable.tsx
- frontend/src/widgets/asset-management-draggable-table/ui/SortingButton.tsx
- 드래그 앤 드롭 변경사항 적용
- 헤더 정렬 기능 구현
> GROW-137 feature: 정렬 기능 구현

- frontend/src/entities/assetManagement/apis/deleteAssetStock.ts
- frontend/src/entities/assetManagement/apis/patchAssetStock.ts
- frontend/src/entities/assetManagement/apis/postAssetStock.ts
- frontend/src/entities/assetManagement/apis/putAssetField.ts
- frontend/src/entities/assetManagement/atoms/lastUpdatedAtAtom.ts
- frontend/src/entities/assetManagement/queries/useDeleteAssetStock.ts
- frontend/src/entities/assetManagement/queries/usePatchAssetStock.ts
- frontend/src/entities/assetManagement/queries/usePostAssetStock.ts
- frontend/src/entities/assetManagement/queries/usePutAssetField.ts
- frontend/src/shared/lib/query-keys.ts
- frontend/src/shared/ui/PriceDisplay.tsx
- frontend/src/shared/ui/table/AddRowButton.tsx
- frontend/src/shared/ui/table/DeleteRowIconButton.tsx
- frontend/src/shared/ui/table/Table.tsx
- frontend/src/widgets/Summary/ui/Summary.tsx
- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementDraggableTable.tsx
- frontend/src/widgets/assets-management-tab-bar/ui/AssetManagementTabBar.tsx
- 테이블 셀 수정시 자동 저장 요청
- 행 추가 시에만 데이터 새로 갱신 (id 값 갱신 필요하기 때문)
- 셀 변경 시에는 클라이언트 메모리 데이터 새로 갱신하지 않음
- 저장 성공시 최근 저장 성공 일시 저장 및 표현 UI 추가
> GROW-135 feature: 테이블 셀 자동 저장 기능 구현

- frontend/package.json
- frontend/src/components/ui/tooltip.tsx
- frontend/src/shared/ui/Tooltip.tsx
- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementDraggableTable.tsx
- frontend/src/widgets/assets-accumulate-trend/ui/AssetsAccumulateTrendTooltip.tsx
- frontend/yarn.lock
> GROW-148 feature: 테이블 헤더 필수 필드 및 툴팁 기능 적용

- frontend/src/app/asset-management/overview/loading.tsx
- frontend/src/app/asset-management/overview/page.tsx
- frontend/src/app/asset-management/sheet/error.tsx
- frontend/src/app/asset-management/sheet/page.tsx
- frontend/src/components/ui/skeleton.tsx
- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementDraggableTable.tsx
- frontend/src/widgets/asset-management-guest-access-guide-button/ui/AssetManagementAccessGuideButton.tsx
- frontend/src/widgets/join-dialog/ui/UserAgreement.tsx
> GROW-149 fix: 로딩 상태 처리 및 에러 바운더리 추가

- frontend/src/shared/ui/DragAndDropDropdown.tsx
- frontend/src/shared/ui/calendar/calendar.tsx
- onTounctStart 이벤트 관련 ts 에러 수정
> GROW-151 fix: 빌드 에러 수정

- frontend/src/entities/assetManagement/apis/deleteAssetStock.ts
- frontend/src/entities/assetManagement/apis/getBrokerAccountList.ts
- frontend/src/entities/assetManagement/apis/getItemNameList.ts
- frontend/src/entities/assetManagement/apis/patchAssetStock.ts
- frontend/src/entities/assetManagement/apis/postAssetStock.ts
- frontend/src/entities/assetManagement/apis/putAssetField.ts
- frontend/src/shared/ui/BarChart.tsx
- frontend/src/shared/ui/DonutChart.tsx
- frontend/src/shared/utils/fetchWithTimeout.ts
- frontend/src/widgets/asset-management-draggable-table/api/getAssetsStock.ts
- frontend/src/widgets/estimate-dividend/ui/EstimateDividendClient.tsx
- frontend/src/widgets/join-dialog/api/checkValidateNickname.ts
- frontend/src/widgets/join-dialog/api/updateNickname.ts
- 예상 배당액 및 도넛 차트에서 *10000 된 금액으로 표시되는 문제 수정
- fetch 캐싱 시간 10분으로 설정
- 추후 fetch사용하실 때 fetch 대신 fetchWithTimeout 유틸을 사용해 fetching 작업해 주세요! (timeout 및 캐싱 시간 설정 상의 이유)
> GROW-150 fix: 예상 배당액, 도넛 차트 금액 오표시 수정 / fetch 캐싱 시간 10분으로 설정 

- frontend/src/widgets/asset-management-draggable-table/quries/useGetAssetStocks.ts
- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementDraggableTable.tsx
- 윈도우 포커스 벗어난 후 재 수정시 수정 안되던 문제 해결
- 테이블 필드 정렬 적용 안되던 문제 수정
> GROW-152 fix: 테이블 시트 수정 관련 버그 수정

- frontend/next.config.mjs
- frontend/src/entities/assetManagement/apis/deleteAssetStock.ts
- frontend/src/entities/assetManagement/apis/getBrokerAccountList.ts
- frontend/src/entities/assetManagement/apis/getItemNameList.ts
- frontend/src/entities/assetManagement/apis/patchAssetStock.ts
- frontend/src/entities/assetManagement/apis/postAssetStock.ts
- frontend/src/entities/assetManagement/apis/putAssetField.ts
- frontend/src/shared/index.ts
- frontend/src/shared/utils/getBaseUrl.ts
- frontend/src/widgets/asset-management-draggable-table/api/getAssetsStock.ts
- http -> https로 인해 발생하는 요청 에러 수정
> GROW-153: fix: next config 프록시 설정 추가

- frontend/src/widgets/assets-accumulate-trend/api/getAssetSaveTrent.ts
- frontend/src/widgets/assets-accumulate-trend/ui/AssetsAccumulateTrend.tsx
> GROW-154: feat: 자산 적립 추이 api 연결

- frontend/src/shared/ui/DatePicker.tsx
- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementDraggableTable.tsx
> GROW-155 fix: 구매일자 초기값 undefined 로 수정

- frontend/src/widgets/asset-management-summary-card/ui/AssetManagementMobileSummary.tsx
- frontend/src/widgets/asset-management-summary-card/ui/AssetManagementSummaryCard.tsx
- 카드 컴포넌트 통일화
- 모바일 패딩값 수정
- 소숫점 자리 표기법 수정
> GROW-156 fix: 상단 요약 컴포넌트 패딩 값 및 소숫점 자리 표기 법 수정

- frontend/package.json
- frontend/src/entities/assetManagement/queries/usePatchAssetStock.ts
- frontend/src/shared/ui/NumberInput.tsx
- frontend/src/shared/utils/number.ts
- frontend/src/stories/NumberInput/NumberInput.stories.tsx
- frontend/src/widgets/asset-management-draggable-table/api/mock.ts
- frontend/src/widgets/asset-management-draggable-table/quries/useGetAssetStocks.ts
- frontend/src/widgets/asset-management-draggable-table/types/table.d.ts
- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementDraggableTable.tsx
- frontend/yarn.lock
- 매입가 입력 원화, 달러 유기적으로 변동 안되던 문제 수정
- update 성공시 invalidate 진행하도록 수정
- 넘버 인풋 가격 단위 입력시 옳바르게 동작하지 않던 문제 수정
> GROW-157 fix: 테이블 시트 버그 수정

- frontend/src/components/ui/resizable.tsx
- frontend/src/shared/ui/table/TableColumn.tsx
- frontend/src/shared/ui/table/TableHeader.tsx
- frontend/src/widgets/asset-management-draggable-table/ui/SortingButton.tsx
- 헤더 정렬 버튼 호버 이펙트 개선
- 헤더 리사이즈 핸들러 호버 이펙트 개선 및 너비 개선
- 헤더 전체가 grap 커서가 되지 않도록 수정
> GROW-144 fix: 테이블 헤더 기능 개선

- frontend/src/shared/hooks/useDragAndDrop.tsx
- frontend/src/shared/ui/table/TableColumn.tsx
- frontend/src/shared/ui/table/TableHeader.tsx
- 테이블 헤더 드래그 앤 드롭 UI 버그 픽스
- 테이블 헤더 드래그 앤 드롭 사용성 개편
> GROW-165 fix: 테이블 헤더 드래그 앤 드롭 UI 수정 및 사용성 개편

- frontend/src/shared/ui/table/Table.tsx
> GROW-164 feature: 가로 스크롤 보여지도록 수정

- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementDraggableTable.tsx
- 데이트피커 셀 너비 넓어지면 정렬 가운데로 되던 문제 수정
> GROW-167 fix: 데이트피커 셀 너비 넓어지면 정렬 가운데로 되던 문제 수정

- frontend/src/shared/ui/calendar/calendar.tsx
- disabled된 날짜에는 현재 날짜 및 선택된 날짜 이펙트 적용 되지 않도록 수정
> GROW-169 fix: 캘린더 컴포넌트 현재 날짜 및 선택된 날짜 이펙트 적용 버그 수정

- frontend/src/entities/assetManagement/apis/getItemNameList.ts
- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementDraggableTable.tsx
- frontend/src/widgets/asset-management-draggable-table/ui/ItemNameCell.tsx
- 종목 리스트 API 변경사항 반영
- 영어 이름 검색 가능하도록 수정
> GROW-174 fix: 종목 리스트 API 변경사항 반영

- frontend/src/entities/assetManagement/queries/usePatchAssetStock.ts
- frontend/src/entities/assetManagement/queries/usePostAssetStock.ts
- frontend/src/widgets/asset-management-draggable-table/atoms/cellErrorAtom.ts
- jotai 전역 상태 사용해서 셀 에러에 대한 정보 저장
> GROW-162: feature: 응답 오류 발생시 에러 상태 저장하는 기능 구현

- frontend/src/entities/assetManagement/queries/usePatchAssetStock.ts
- frontend/src/entities/assetManagement/queries/usePostAssetStock.ts
- frontend/src/shared/ui/table/Table.tsx
- frontend/src/shared/ui/table/TableCell.tsx
- frontend/src/shared/ui/table/TableColumn.tsx
- frontend/src/widgets/asset-management-draggable-table/atoms/cellErrorAtom.ts
- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementDraggableTable.tsx
- frontend/src/widgets/assets-management-tab-bar/ui/AssetManagementTabBar.tsx
- 리액트 쿼리 훅에서 상태 코드 제대로 확인하고 있지 않던 문제 수정
- 테이블 컴포넌트 셀 에러 표현할 수 있도록 기능 추가
- 에러 상태 전달 및 에러 UI 구현
- invalidate 쿼리 옵션 수정
> GROW-163: 테이블 셀 에러 UI 구현

- frontend/src/app/asset-management/sheet/loading.tsx
- frontend/src/components/ui/skeleton.tsx
- frontend/src/shared/ui/NoDataMessage.tsx
- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementDraggableTable.tsx
- frontend/src/widgets/asset-management-summary-card/ui/AssetManagementSkeleton.tsx
- frontend/src/widgets/asset-management-summary-card/ui/AssetSheetSummary.tsx
- frontend/src/widgets/assets-accumulate-trend/ui/AssetsAccumulateTrend.tsx
> GROW-175 fix: 자산 관리 시트 로딩 UI 개선

- frontend/src/widgets/assets-accumulate-trend/ui/AssetsAccumulateTrend.tsx
> GROW-176 fix: 자산 적립 추이 차트 모바일 UI 수정

- frontend/src/widgets/join-dialog/api/updateNickname.ts
- frontend/src/widgets/join-dialog/ui/NicknameSetup.tsx
> GROW-178 fix: 회원가입 리다이렉트 오류 수정

- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementSheet.tsx
> GROW-179 fix: 변수 초기화 전 접근 에러 수정

- frontend/src/widgets/asset-management-draggable-table/atoms/useInitializeAtoms.ts
- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementSheet.tsx
> GROW-181 fix: 아톰 초기화 되도록 수중

- frontend/src/shared/ui/DragAndDropDropdown.tsx
- 체크 박스 해제 하더라고 순서 변경 안되도록 코드 수정
> GROW-184 fix: 드래그 앤 드롭다운 체크박스 해제하더라도 순서 변경 안되도록 수정

- frontend/src/shared/ui/calendar/calendar.tsx
- variant가 disabled가 아닌 경우에만 호버 이펙트 배경 나타나도록 수정
> GROW-182 fix: disabled 된 날짜는 hover 이펙트 나타나지 않도록 수정

- frontend/src/app/page.tsx
- frontend/src/entities/user/api/getUser.ts
- frontend/src/widgets/HomeGuestAccessGuide/ui/HomeGuestAccessGuideButton.tsx
- frontend/src/widgets/HomeGuestAccessGuide/ui/HomeGuestAccessGuideButtonClient.tsx
> GROW-191 fix: 비회원에게 표시되는 플로우 버튼이 로그인 시 잠깐 표시되는 문제 수정

- frontend/src/entities/assetManagement/queries/usePutAssetField.ts
> GROW-187 fix: 시트 필드 변경시 invalidate 진행 하도록 수정

- frontend/src/entities/assetManagement/queries/usePutAssetField.ts
- frontend/src/widgets/asset-management-draggable-table/hooks/useHandleAssetStockField.ts
- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementSheet.tsx
> GROW-188 fix: 모든 필드 추가시 에러 발생하는 문제 수정

- frontend/src/shared/ui/table/TableColumn.tsx
- errorMesage 인자를 전달하고 있지 않던 문제 수정
> GROW-193 fix: 자산 관리 시트 에러 메세지 제대로 표현할 수 있도록 수정

- frontend/instrumentation.ts
- frontend/next.config.mjs
- frontend/package.json
- frontend/sentry.client.config.ts
- frontend/sentry.edge.config.ts
- frontend/sentry.server.config.ts
- frontend/src/app/asset-management/sheet/error.tsx
- frontend/src/app/global-error.tsx
- frontend/yarn.lock
> GROW-195 feature: 센트리 모니터링툴 추가

- frontend/next.config.mjs
- frontend/sentry.client.config.ts
- frontend/sentry.edge.config.ts
- frontend/sentry.server.config.ts
- frontend/src/widgets/asset-management-summary-card/ui/AssetSheetSummary.tsx
> GROW-195 fix: 센트리 모니터링 툴 gemischool 계정으로 수정

- frontend/src/shared/ui/table/AddRowButton.tsx
> GROW-196 fix: 행 추가 버튼 그룹 호버시 동작하도록 수정

- frontend/src/widgets/asset-management-summary-card/ui/AssetManagementSkeleton.tsx
- 자산 관리 시트 요약 컴포넌트 로딩 스켈레톤 높이 100px로 수정
> GROW-198 fix: 로딩 스켈레톤 높이 100px로 수정

- frontend/.gitignore
- frontend/holiday-kr.mjs
- frontend/package.json
> GROW-158 fix: 공휴일 정보 갱신 자동화

- frontend/package.json
- frontend/src/app/layout.tsx
- frontend/yarn.lock
> GROW-204 feature: ga 설정 추가

- frontend/src/components/ui/resizable.tsx
- frontend/src/shared/ui/table/Table.tsx
- frontend/src/shared/ui/table/TableCell.tsx
- frontend/src/shared/ui/table/TableColumn.tsx
- frontend/src/shared/ui/table/TableHeader.tsx
> GROW-205 fix: 테이블 헤더 리사이즈 핸들러 위치 및 UI 수정

- frontend/src/components/ui/resizable.tsx
- frontend/src/shared/ui/table/DeleteRowIconButton.tsx
- frontend/src/shared/ui/table/Table.tsx
- frontend/src/shared/ui/table/TableCell.tsx
- frontend/src/shared/ui/table/TableColumn.tsx
- frontend/src/shared/ui/table/TableHeader.tsx
- Resizable 핸들러 기존 코드로 수정
- border를 통한 구분자에서 div 태그로 별도의 디바이더 만드는 방식으로 수정
> GROW-207 fix: 테이블 드래그 앤 드롭시 삽입될 위치 보여주는 UI 짤리던 문제 수정

- frontend/src/shared/ui/table/Table.tsx
- frontend/src/shared/ui/table/TableColumn.tsx
- frontend/src/widgets/asset-management-draggable-table/quries/useGetAssetStocks.ts
- key prop 오류 수정
- 통화 종류에 따른 정렬 로직 추가
> GROW-206 fix: 통화 문제로 인해 발생한 정렬 오류 수정

- frontend/src/shared/ui/table/Table.tsx
- frontend/src/shared/ui/table/TableColumn.tsx
- frontend/src/widgets/asset-management-draggable-table/hooks/useAssetManagementSheetWidth.ts
- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementSheet.tsx
- minimumWidth의 크기를 defaultSize의 절반으로 수정
- tableWidth 계산 로직 수정
> GROW-209 fix: 자산 관리 시트 리사이즈 기능 동작하지 않던 문제 수정

- frontend/src/shared/ui/table/Table.tsx
- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementSheet.tsx
- 최소 사이즈 올바르게 계산 되도록 수정
- 매입가 배경색 흰색으로 수정
> GROW-208 fix: 매입가 배경 색상 희색으로 수정

- frontend/src/widgets/asset-management-draggable-table/hooks/useHandleAssetStock.ts
- id 값이 임시 생성된 id값(0보다 작은 경우) invalidate를 수행하지 않도록 수정
> GROW-200 fix: id가 임시 생성된 id 값이라면 invalidate 되지 않도록 수정

- frontend/src/shared/ui/table/Table.tsx
- frontend/src/shared/ui/table/TableColumn.tsx
- frontend/src/widgets/asset-management-draggable-table/constants/essentialFields.ts
- frontend/src/widgets/asset-management-draggable-table/ui/ItemNameCell.tsx
- 드래그 앤 드롭 안되는 문제 수정
- 코드 이용해 종목 명 검색하는 기능 추가
> GROW-199 feature: 코드 검색 기능 추가 및 드래그 앤 드롭 안정화

- frontend/src/widgets/asset-management-draggable-table/api/getAssetsStock.ts
- frontend/src/widgets/asset-management-draggable-table/constants/allField.ts
- frontend/src/widgets/asset-management-draggable-table/types/table.d.ts
> GROW-232 feature: 자산 관리 시트 데이터 요청 API 변경사항 대응

- frontend/src/entities/assetManagement/apis/postAssetStock.ts
- frontend/src/entities/assetManagement/queries/usePostAssetStock.ts
- frontend/src/widgets/asset-management-draggable-table/api/getAssetsStock.ts
- frontend/src/widgets/asset-management-draggable-table/hooks/useHandleAssetStock.ts
- frontend/src/widgets/asset-management-draggable-table/quries/useGetAssetStocks.ts
> GROW-234 fix: 자산 관리 시트 데이터 요청 API 변경사항 대응 

- frontend/src/shared/utils/getBaseUrl.ts
- frontend/src/widgets/asset-management-draggable-table/api/getAssetsStock.ts
- frontend/src/widgets/asset-management-draggable-table/hooks/useHandleAssetStockField.ts
- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementSheet.tsx
- frontend/src/widgets/asset-management-draggable-table/utils/fieldItemFactory.ts
> fix: API 변경 이후 발생하는 테이블 IDE에러 수정

- frontend/src/features/assetManagement/consts/column-type.ts
- frontend/src/shared/ui/table/Table.tsx
- frontend/src/widgets/asset-management-draggable-table/hooks/useHandleAssetStock.ts
- frontend/src/widgets/asset-management-draggable-table/types/table.d.ts
- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementSheet.tsx
- frontend/src/widgets/asset-management-draggable-table/utils/parseStockForMultipleCurrency.ts
> GROW-213 feautre: API 변경점 최소 대응 작업 완료

- frontend/src/entities/assetManagement/apis/getItemNameList.ts
- frontend/src/shared/ui/table/Table.tsx
- frontend/src/widgets/asset-management-draggable-table/constants/essentialFields.ts
- frontend/src/widgets/asset-management-draggable-table/types/table.d.ts
- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementSheet.tsx
- frontend/src/widgets/asset-management-draggable-table/utils/parseStockForMultipleCurrency.ts
- 현재 오류가 너무 많아 부모 행만 추출해서 UI만 그리도록 수정. 작은 단위로 기능 도입하며 버그 수정해나갈 예정임.
> GROW-256 fix: 우선 부모 행만 추출해서 UI 그리도록 수정

- frontend/src/widgets/asset-management-draggable-table/constants/fieldWidth.ts
- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementSheet.tsx
> GROW-258 feature: 자산 관리 시트 헤더 매매 필드 컴포넌트 적용

- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementSheet.tsx
> GROW-259 fix: 자산 관리 시트 계좌 종류 필드 컴포넌트 반환 값 수정

- frontend/next.config.mjs
- API 프록시 및 turbo resolveAlias 관련 설정을 삭제했습니다.
- 설정 간소화를 위해 불필요한 옵션을 제거하였습니다.
> refactor(config): rewrites 및 experimental 설정 제거

- frontend/next.config.mjs
- frontend/src/shared/utils/getServiceUrl.ts
- frontend/src/widgets/asset-management-draggable-table/api/getAssetsStock.ts
- `next.config.mjs`에 API 경로 재작성(rewrite) 설정을 추가했습니다.
- 서버와 클라이언트 환경에 따라 적합한 서비스 URL을 반환하는 `getServiceUrl` 유틸리티 함수를 새로 작성했습니다.
- API 호출 로직에서 기존 상수 `SERVICE_SERVER_URL` 대신 `getServiceUrl` 함수를 사용하도록 수정했습니다.
> feat(api): API 경로 재작성 및 서비스 URL 유틸리티 추가

- frontend/next.config.mjs
- 변경된 리다이렉트 경로에 "/api" 접두사가 추가되었습니다.
- 올바른 엔드포인트로 요청이 전달되도록 경로 오류를 수정했습니다.
> fix(config): API 리다이렉트 경로 수정

- frontend/src/shared/utils/getServiceUrl.ts
서비스 URL이 하드코딩된 상태에서 환경 변수 `NEXT_PUBLIC_API_URL`을 통해 동적으로 설정되도록 수정했습니다. 환경에 따라 유연하게 API URL을 변경할 수 있도록 하기 위함입니다.
> feat(utils): 환경 변수를 사용하도록 서비스 URL 변경

- frontend/src/widgets/asset-management-draggable-table/api/getAssetsStock.ts
- getAssetsStock 함수에서 SERVICE_SERVER_URL 의존성을 제거하고 getServiceUrl로 대체했습니다.
- 불필요한 SERVICE_SERVER_URL 로그를 삭제하고 getServiceUrl 로그를 추가했습니다.
이를 통해 코드 유지보수성을 향상하고 의존성을 줄였습니다.
> refactor(api): SERVICE_SERVER_URL 의존성 제거 및 로그 수정

- frontend/src/entities/assetManagement/apis/getAssetsStock.ts
- frontend/src/shared/utils/getServiceUrl.ts
- `fetchWithTimeout` 대신 기본 `fetch`를 사용하도록 수정했습니다.
- `getServiceUrl` 함수의 불필요한 조건문을 주석 처리하여 코드 간소화 및 가독성 향상을 도모했습니다.
> refactor(assetManagement): fetchWithTimeout 제거 및 fetch로 대체

- frontend/package.json
- frontend/src/entities/assetManagement/apis/getAssetsStock.ts
- frontend/src/shared/lib/axios.ts
- frontend/src/shared/utils/getServiceUrl.ts
- frontend/yarn.lock
- `axios` 패키지를 의존성에 추가하고 기존 fetch 요청을 Axios로 교체했습니다.
- 중복된 유틸리티 함수 `getServiceUrl`을 제거하여 코드 간소화 및 유지보수를 개선했습니다.
- Axios를 통한 에러 핸들링 및 응답 데이터를 보다 직관적으로 처리하도록 수정했습니다.
> 273 버그 수정 요청 경로 문제 수정

- frontend/next.config.mjs
- frontend/vercel.json
- `next.config.mjs`에서 rewrites 설정을 제거하고 vercel.json 파일에 추가했습니다.
- Vercel의 기본 리다이렉션 설정 파일을 활용해 구성 간소화 및 관리 일원화를 구현했습니다.
> chore(config): 리다이렉션 설정 vercel.json으로 분리

- frontend/src/entities/asset-management/queries/useGetAssetStocks.ts
- frontend/src/shared/ui/NumberInput.tsx
- frontend/src/widgets/asset-management-draggable-table/hooks/useAssetManagementSheetWidth.ts
- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementSheet.tsx
기존 정렬 타입(date, string, number)에 더해 price, amount, ratio 타입을 추가했습니다.  
이에 따라 새로운 정렬 로직이 적용되었으며, 관련 상수 참조를 제거하고 코드 구조를 정리했습니다.
> 268 기능 수정 총 자산 갯수 서브행 기준으로 표기되로록 수정

- frontend/src/widgets/header/ui/Header.tsx
- frontend/src/widgets/header/ui/Menu.tsx
- frontend/tailwind.config.ts
- Header 컴포넌트의 shadow-header 박스 그림자와 여백 수정
- 불필요한 usePathname 함수 및 관련 코드 제거
- LogoLink와 Menu 컴포넌트에서 여백 및 href 경로 개선
- Tailwind 설정에 header 박스 그림자 추가
> style(header): UI 스타일 조정 및 불필요 코드 제거

- frontend/src/widgets/footer/ui/Footer.tsx
- frontend/tailwind.config.ts
- 푸터 레이아웃을 모바일 환경에 맞게 수정하여 유연성을 개선함.
- 서비스 이용약관 및 개인정보처리방침 링크 추가.
- Tailwind 설정에 `mobile-459` 반응형 스크린 속성을 적용하고 primary 색상을 rgba로 변경.
> feat(footer): 모바일 UI 개선 및 레이아웃 수정

- frontend/src/widgets/header/ui/Header.tsx
- 헤더에 `shadow-header` 클래스와 높은 z-index를 추가했습니다.
- UI 개선을 위해 시각적 명확성을 제공하기 위함입니다.
>   style(header): 헤더에 그림자 및 z-index 추가

- frontend/.storybook/main.ts
- frontend/.storybook/preview.ts
- frontend/src/stories/GNB/Menu.stories.tsx
- frontend/src/stories/GNB/MenuItem.stories.tsx
- frontend/src/stories/IncDecRate/IncDecRate.stories.tsx
- frontend/src/stories/Input/InputWithImage.stories.tsx
- frontend/src/stories/LineButton/LineButton.stories.tsx
- frontend/src/stories/SegmentedButton/SegmentedButton.stories.tsx
- frontend/src/stories/이용약관/UserAgreement.stories.tsx
- frontend/src/widgets/join-dialog/ui/UserAgreement.tsx
약관 동의 체크박스 옆에 '약관보기' 버튼을 추가하여 사용자가 약관 내용을 쉽게 확인할 수 있도록 개선하였습니다. UI를 사용성 중심으로 조정했습니다.
> feat(join-dialog): 약관보기 버튼 추가

- frontend/src/app/layout.tsx
- frontend/src/shared/ui/Tooltip.tsx
- frontend/src/widgets/asset-management-draggable-table/atoms/cellErrorAtom.ts
- frontend/src/widgets/asset-management-draggable-table/hooks/useHandleAssetStock.ts
- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementSheet.tsx
- frontend/src/widgets/asset-management-draggable-table/ui/SellBuyButton.tsx
- `Tooltip` 컴포넌트에 `open` 속성을 추가하고 구조를 최적화했습니다.
- 매매 버튼에 툴팁을 적용해 사용자에게 추가적인 안내를 제공합니다.
- 툴팁 스타일 및 위치 조정을 위한 옵션(`side`, `sideOffset`)을 추가했습니다.
- 에러 객체에 `value` 필드를 추가해 툴팁과의 연동을 지원합니다.
> feat(tooltips): Tooltip 컴포넌트 개선 및 매매 버튼에 기능 추가

- frontend/src/widgets/header/ui/Menu.tsx
> fix(header): 메뉴 이름 수정

- frontend/src/widgets/header/ui/Header.tsx
- frontend/src/widgets/header/ui/Menu.tsx
- 헤더 컴포넌트에서 중복된 CSS 클래스 및 상쇄되는 스타일 제거
- `flex` 요소 간격을 `gap`으로 통일하여 가독성과 유지보수성 개선
- 모바일 및 비모바일 레이아웃 처리를 위한 클래스 추가
> style(header): 불필요한 클래스 제거 및 공간 조정 리팩토링

- frontend/src/shared/ui/NumberInput.tsx
- frontend/src/shared/ui/table/Table.tsx
- frontend/src/shared/ui/table/TableCell.tsx
- frontend/src/shared/ui/table/TableColumn.tsx
- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementSheet.tsx
- `tableId`를 활용해 에러 메시지와 테두리 위치를 정확히 계산하도록 수정하였습니다.
- 셀 컴포넌트의 에러 처리 로직을 최적화하고 불필요한 DOM 접근을 줄였습니다.
> feat(table): table 및 셀 컴포넌트에 tableId 전달 및 에러 처리 개선

- frontend/src/app/globals.css
- frontend/src/entities/user/api/getUser.ts
- frontend/src/features/login/api/checkIsJoined.ts
- `getUser` 함수에서 유저 데이터가 없을 경우 `null` 반환하도록 수정
- `checkIsJoined` 로직에 유저 데이터가 없는 경우 `false`를 반환하는 처리 추가
- `globals.css`에 body와 html의 `font-synthesis` 초기화 스타일 적용
> fix(user, login): 유저 데이터 누락 상황 처리 추가

- frontend/src/shared/ui/LineChart.tsx
차트 설정 로직을 간소화하고 가독성을 개선했습니다.
- chartInstance.setOption 직접 호출로 중복된 변수 제거
- 불필요한 symbol 설정 및 emphasis 옵션 삭제
- legend 스타일 필드 itemWidth와 itemHeight 추가 및 icon 정의 개선
> refactor(LineChart): 차트 옵션 설정 로직 정리 및 불필요 코드 제거

- frontend/src/widgets/top-10-selected-by-rich-person/ui/Top10SelectedByRichPersonItem.tsx
- 최소 너비를 `min-w-[102px]`에서 `xl:min-w-[108px]`로 수정
- 반응형 레이아웃에서 아이템 정렬 개선을 목표로 함
> style(ui): 반응형 디자인을 위한 최소 너비 조정

- frontend/src/shared/ui/FloatingButton.tsx
- 버튼의 최소 너비, 패딩, 모서리 둥글기 등을 수정하여 디자인 개선
- 텍스트가 길 경우 잘리지 않도록 overflow 처리 추가
- 아이콘 위치를 중앙 정렬로 수정
> style(ui): cta 버튼 패딩 수정

- frontend/src/shared/ui/DonutChart.tsx
툴팁 UI를 개선하고 가독성을 높이기 위해 스타일 수정 및 숫자 포맷팅 로직을 추가하였습니다.
- `commaizeNumber`와 `ceil` 유틸을 사용해 숫자 포맷팅 적용
- 툴팁 레이아웃 및 스타일 변경으로 시각적 개선
> feat(DonutChart): 툴팁 UI 개선 및 숫자 포맷팅 적용

- frontend/src/shared/ui/DonutChart.tsx
- frontend/src/shared/ui/LineChart.tsx
- frontend/tailwind.config.ts
- DonutChart와 LineChart의 툴팁에 그림자 스타일 적용
- tailwind.config에 chart-tooltip 스타일 정의 추가
> feat(chart): 툴팁에 그림자 스타일 추가

- frontend/src/components/ui/dialog.tsx
- frontend/src/features/login/ui/LoginDialog.tsx
- frontend/tailwind.config.ts
- 필요 없는 주석 제거 및 다이얼로그 z-index 변경
- 로그인 다이얼로그 텍스트에 반응형 br 태그 추가
- Tailwind에 새로운 브레이크포인트(min-376, min-545) 설정 추가
> style(ui): 로그인을 위한 UI 수정 및 Tailwind 브레이크포인트 추가

- frontend/src/shared/utils/number.ts
- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementSheet.tsx
- 더 적합한 반올림 함수를 사용하기 위해 ceil에서 round로 교체
- 관련 import 및 함수 호출 부분 업데이트
- 환율 변환 및 소수점 처리를 명확히 하기 위한 코드 개선
> refactor(number-utils): ceil 함수 대신 round 함수로 변경

- frontend/src/widgets/asset-management-draggable-table/ui/SellBuyButton.tsx
window 객체 존재 여부를 확인하는 조건을 추가하여 서버 사이드 렌더링 환경에서도 오류가 발생하지 않도록 수정했습니다.
- `typeof window !== "undefined"` 조건 추가
- SSR 환경에서 document.body 접근 시 예외 방지
> fix(ui): 버튼 렌더링 조건 수정

- frontend/src/shared/ui/table/HandleColumDisplayButton.tsx
- frontend/src/shared/ui/table/Table.tsx
- 종목명, 매매, 수량, 매매일자로 필수 항목 텍스트를 업데이트함
- 불필요한 제네릭 매개변수 제거로 코드 간결화
> fix(table): 필수 항목 텍스트 수정

- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementSheet.tsx
- 해외 주식 통화 설정 텍스트에 폰트 굵기와 색상 추가
- UI 일관성 향상을 위해 스타일 개선
> style(asset-management): 텍스트 스타일 수정

- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementSheet.tsx
- 부모 항목이고 현재 통화가 USD인 경우, 환율 변환 로직이 올바르게 동작하도록 수정
- 기존에는 KR 통화 조건을 잘못 포함하여 일부 환산이 불필요하게 처리됨
> fix(asset-management-sheet): 배당금, 수익금이 높게 나오던 문제 수정

- frontend/src/shared/ui/IncDecRate.tsx
- frontend/src/shared/ui/PriceDisplay.tsx
- frontend/src/shared/utils/number.ts
- frontend/src/widgets/investment-performance-chart/ui/PercentWithTitle.tsx
- frontend/src/widgets/my-stocks/ui/StockTable.tsx
- 모든 수치를 소수점 두 자리까지 표시하도록 수정
- RoundedRate, StockTable 등에서 toFixed(2)를 적용하여 일관성 유지
- 누락된 정보 전달 방지 및 데이터 가독성 개선
> fix(number-format): 소수점 두 자리까지 반올림 처리로 수정

- frontend/src/app/api/auth/kakao/callback/route.ts
- frontend/src/app/api/auth/kakao/route.ts
- frontend/src/features/login/KakaoLoginButton.tsx
- frontend/src/features/login/NaverLoginButton.tsx
- frontend/src/shared/ui/LineButton.tsx
- 카카오 및 네이버 OAuth 로그인 요청 방식을 경로 호출에서 폼 제출로 변경
- `LineButton` 컴포넌트 재사용으로 버튼 스타일 통일
- 불필요한 코드 및 파일 제거로 코드 간소화
> refactor(login): OAuth 인증 방식 업데이트

- frontend/src/app/api/auth/google/callback/route.ts
- 중복된 오류 처리 코드를 제거하여 코드 간소화
- 로그인 실패 시 에러 메시지를 쿼리 파라미터에 추가하여 디버깅 용이성 개선
> fix(auth): 구글 콜백 오류 처리 수정

- frontend/src/widgets/asset-management-draggable-table/ui/ItemNameCell.tsx
- 종목명 입력란에 "종목명을 입력해 주세요." 플레이스홀더를 추가
> feat(asset-management-draggable-table): 입력 필드에 플레이스홀더 추가

- frontend/src/shared/ui/NumberInput.tsx
- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementSheet.tsx
- `useRef` 추가로 input 엘리먼트 접근 및 커서 제어 지원
- 포커스 상태에 따라 값 포맷팅 동작 분리
- `region` 기본값 "KRW" 설정 및 통화 접두사 함수 분리
- 불필요한 핸들러 코드 간소화 및 로직 가독성 향상
> refactor(NumberInput): 입력 포맷 및 포커스/블러 로직 개선 및 수량 입력 포커스시 0이 지워지도록 수정

- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementSheetHeader.tsx
- 새로운 필드("수익금", "배당금")에 대한 툴팁 기능 추가
- 필드에 따라 동적으로 제목 반환 기능(getTitle) 구현
- 일부 툴팁 설명 텍스트 수정으로 가독성 개선
> feat(asset-management): 툴팁 및 제목 로직 확장

- frontend/src/shared/constants/api.ts
- 환경 변수 접근 로직을 함수(getNodeEnv)로 분리하여 코드 가독성을 향상시킴
- NODE_ENV와 NEXT_PUBLIC_NODE_ENV 처리 통합으로 브라우저와 서버 환경 고려
> refactor(constants): 환경 변수 접근 로직 분리 및 함수화

- frontend/src/app/layout.tsx
- frontend/src/app/page.tsx
- frontend/src/features/user-feedback/index.ts
- frontend/src/features/user-feedback/ui/UserFeedbackButton.tsx
- frontend/src/widgets/footer/ui/Footer.tsx
- 사용자 피드백 버튼(UserFeedbackButton) 컴포넌트를 추가하여 피드백 제공 기능 제공
- 레이아웃 구조를 개선하여 가독성과 유지보수성을 향상
- Footer에 서비스 제공 정보 관련 추가 설명을 포함
> feat(layout): 사용자 피드백 버튼 추가 및 레이아웃 개선

- frontend/src/shared/ui/PrimaryButton.tsx
- frontend/src/shared/ui/checkbox/Checkbox.tsx
- frontend/src/widgets/deactivate-widget/ui/Deactivate.tsx
- PrimaryButton 및 Checkbox 컴포넌트에서 색상 클래스명(primary) 수정
- Deactivate 위젯에서 폰트 크기 및 여백 스타일 업데이트
- 텍스트 스타일(class) 구조 개선으로 일관성 유지
> style(ui): 기본 스타일 수정 및 클래스명 개선

- frontend/src/widgets/my-page/ui/ChangeNickname.tsx
- 닉네임 입력 시 최대 12자를 초과하지 않도록 제한하는 로직 추가
- setNickname 호출 전에 trim과 글자 수 검사를 수행하도록 handleNickname 함수 구현
> feat(ChangeNickname): 닉네임 글자 수 제한 기능 추가

- frontend/src/widgets/footer/ui/Footer.tsx
- 푸터 하단에 ⓒ 2025. ollass All rights reserved. 문구 추가
- mobile-459 뷰포트에서 상단 여백(pt)을 52px로 수정
> feat(footer): 저작권 문구 추가 및 스타일 수정

- frontend/src/shared/ui/Card.tsx
- frontend/src/shared/ui/PriceDisplay.tsx
- frontend/src/widgets/Summary/ui/SummaryCard.tsx
- Card 컴포넌트에서 fontSize 관련 로직 제거
- PriceDisplay 컴포넌트와 SummaryCard에서 폰트 스타일 수정 및 정리
- 코드 가독성을 위해 불필요한 클래스명 및 구조 단순화
> refactor(ui): 불필요한 스타일 및 폰트 크기 로직 제거

- frontend/src/widgets/footer/ui/Footer.tsx
- 잘못된 이메일 주소를 `ollass.help@gmail.com`으로 수정
- 사용자 문의 처리를 위한 정확한 정보 제공
> fix(footer): 이메일 주소 업데이트

- frontend/src/shared/ui/DonutChart.tsx
- 모바일에서 범례(legend) 너비를 60%에서 70%로 변경
- maxNameLength 계산 시 여백값 수정 및 소형 화면에서 최댓값 수정
- 레이아웃 속성에 overflow 및 ellipsis 옵션 추가
- space 및 percent의 width 값 조정으로 가독성 개선
> refactor(DonutChart): 모바일 및 소형 화면 레이아웃 조정

- frontend/src/entities/asset-management/queries/usePutAssetStock.ts
- frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementSheet.tsx
- frontend/src/widgets/asset-management-draggable-table/ui/SellBuyButton.tsx
- 불필요한 `useDebounce` 호출을 제거하여 성능 최적화
- AssetManagementSheet에서 긴 텍스트를 줄 바꿈 없이 표시되도록 수정
- SellBuyButton에 `flex-shrink-0` 클래스 추가로 레이아웃 깨짐 방지
> refactor(asset-management): 비효율적인 디바운스 제거 및 UI 개선

- frontend/src/widgets/header/ui/DropdownMenus.tsx
- 고객센터 메뉴를 드롭다운에서 제거
- UI 간소화와 사용자 경험 향상을 위해 해당 메뉴 삭제
> feat(header): 고객센터 메뉴 제거

- frontend/src/app/layout.tsx
- Google Analytics와 Google Tag Manager 컴포넌트를 layout.tsx에 통합
- 불필요한 Head 컴포넌트를 제거하고 appleWebApp 설정을 metadata로 이전
> feat(layout): Google Analytics 및 Tag Manager 추가
