frontend/src/app/api/auth/google/callback/route.ts
frontend/src/app/api/auth/kakao/callback/route.ts
frontend/src/app/api/auth/naver/callback/route.ts
frontend/src/app/api/auth/refresh/route.ts
frontend/src/entities/user/api/getUser.ts
frontend/src/shared/index.ts
frontend/src/shared/ui/PriceDisplay.tsx
frontend/src/shared/utils/fetchWithTimeout.ts
frontend/src/widgets/Summary/api/fetchSampleSummary.ts
frontend/src/widgets/Summary/api/fetchSummary.ts
frontend/src/widgets/Summary/ui/Summary.tsx
frontend/src/widgets/Summary/ui/SummaryCard.tsx
frontend/src/widgets/daily-investment-tip/api/fetchTodayTip.ts
frontend/src/widgets/estimate-dividend/api/fetchDummyEstimateDividend.ts
frontend/src/widgets/estimate-dividend/api/fetchEstimateDividend.ts
frontend/src/widgets/estimate-dividend/ui/EstimateDividend.tsx
frontend/src/widgets/estimate-dividend/ui/EstimateDividendClient.tsx
frontend/src/widgets/investment-performance-chart/api/fetchPerformanceAnalysis.ts
frontend/src/widgets/investment-performance-chart/api/fetchPerformanceSampleAnalysis.ts
frontend/src/widgets/market-index/api/fetchIndexes.ts
frontend/src/widgets/market-index/ui/MarketIndexes.tsx
frontend/src/widgets/my-stocks/api/fetchDummyMyStocks.ts
frontend/src/widgets/my-stocks/api/fetchMyStocks.ts
frontend/src/widgets/my-stocks/ui/MyStocks.tsx
frontend/src/widgets/rich-portfolios/api/fetchRichPortfolio.ts
frontend/src/widgets/stock-composition/api/fetchComposition.ts
frontend/src/widgets/stock-composition/api/fetchDummyComposition.ts
frontend/src/widgets/stock-composition/ui/StockCompositionClient.tsx

- fetch() 커스텀 함수 작성: fetchWithTimeout()
- 기본 타임아웃: 5초
- 홈 페이지 컴포넌트에서 데이터 패칭 오류 발생 시 NoDataMessage 컴포넌트가 정상적으로 렌더링되도록 수정
- 로그인 오류 시 NextResponse.redirect를 사용해 홈 페이지로 이동시키도록 수정 (기존: status를 400~500으로 반환하여 뷰포트에 오류 메시지가 그대로 노출되는 문제가 있었음)

[GROW-82] Server 타임아웃 오류 처리

---

frontend/src/shared/ui/IncDecRate.tsx
frontend/src/widgets/top-10-selected-by-rich-person/api/fetchRichPicks.ts
frontend/src/widgets/top-10-selected-by-rich-person/ui/Top10SelectedByRichPerson.tsx
frontend/src/widgets/top-10-selected-by-rich-person/ui/Top10SelectedByRichPersonItem.tsx

- 부자들이 선택한 종목 TOP10 API 연동
- 부자들이 선택한 종목 TOP10 항목 타입 수정 (rank 필드 제거)
- index를 기준으로 rank 유추
- 뷰포트 줄어들 때 name, price가 차지하는 너비가 항목 별로 다른 문제 수정
- truncate한 요소의 부모요소에 overflow-hidden 적용
- max-width 및 w-full 적용

[GROW-86] 부자들이 선택한 종목 TOP10 API 연동

---

frontend/src/app/QueryClientProvider.tsx
frontend/src/app/asset-management/layout.tsx
frontend/src/app/asset-management/overview/page.tsx
frontend/src/app/layout.tsx
frontend/src/shared/constants/api.ts
frontend/src/shared/index.ts
frontend/src/shared/lib/query-keys.ts
frontend/src/widgets/card/Summary.tsx
frontend/src/widgets/card/SummaryCard.tsx
frontend/src/widgets/card/api/getSummary.ts
frontend/src/widgets/card/queries/useGetSummary.ts

- 상단 요약 API 요청 react query 구현
- Suspense Query, Error Boundary로 에러 및 로딩 UI 구현
- 요약 컴포넌트 위치 page에서 layout으로 수정

GROW-87 feat: 요약 상단 페이지 상단 요약 컴포넌트 API 연동

---

frontend/src/app/asset-management/layout.tsx
frontend/src/widgets/tab/Tabs.tsx

- 탭바 반응형 요구사항 정확히 구현되지 않았던 부분들 수정 했습니다.
- border -> hr로 변경한 이유는 border 사용 했을 때 회색 border 위로 검정색 border가 살짝 떠서 보여지던 문제가 있어서 hr 태그 사용하는 방식으로 변경했습니다.

GROW-95 fix: 요약 상단 페이지 탭바 모바일 반응형 UI 수정

---

frontend/src/app/asset-management/layout.tsx
frontend/src/app/asset-management/sheet/page.tsx
frontend/src/widgets/asset-management-summary-card/ui/AssetManagementMobileSummary.tsx
frontend/src/widgets/asset-management-summary-card/ui/AssetManagementSummaryCard.tsx
frontend/src/widgets/asset-management-summary-card/ui/AssetSheetSummary.tsx
frontend/src/widgets/footer/ui/Footer.tsx
frontend/src/widgets/header/ui/Header.tsx
frontend/src/widgets/index.ts

- 자산 관리 시트 요약 컴포넌트 구현
- API 연동
- 레이아웃 수정

GROW-142 feature: 자산 관리 시트 요약 컴포넌트 구현

---

frontend/src/entities/assetManagement/queries/usePatchAssetStock.ts
frontend/src/entities/assetManagement/queries/usePostAssetStock.ts

- 자산 시트 추가, 수정 리액트 쿼리 훅에 성공시에만 invalidate를 진행하는 분기문 추가

GROW-161 fix: 자산 시트 추가, 성공 요청 성공시에만 invalidate 진행하도록 수정

---

frontend/src/shared/ui/NumberInput.tsx

- 숫자 입력 컴포넌트 셀렉터 맨 뒤로 모내지 않도록 onClick 이벤트에서 제거

GROW-185 fix: 숫자 입력 컴포넌트 클릭시 셀럭터 맨 뒤로 선택되는 기능 수정

---

frontend/src/entities/assetManagement/apis/deleteAssetStockParent.ts
frontend/src/entities/assetManagement/apis/deleteAssetStockSub.ts
frontend/src/entities/assetManagement/apis/getBrokerAccountList.ts
frontend/src/entities/assetManagement/apis/getItemNameList.ts
frontend/src/entities/assetManagement/apis/postAssetStock.ts
frontend/src/entities/assetManagement/apis/putAssetField.ts
frontend/src/entities/assetManagement/apis/putAssetStock.ts
frontend/src/shared/index.ts
frontend/src/shared/utils/getBaseUrl.ts
frontend/src/widgets/asset-management-draggable-table/api/getAssetsStock.ts
frontend/src/widgets/assets-accumulate-trend/api/getAssetSaveTrent.ts

- `getBaseUrl` 함수 제거 및 `SERVICE_SERVER_URL` 사용으로 API 경로 일원화
- 관련된 모든 API 호출 코드에서 `getBaseUrl` 대체
- 더 이상 사용되지 않는 `getBaseUrl.ts` 파일 삭제
- 불필요한 유틸 및 컴포넌트(`validateTokenExpiry`, `PortfolioCarousel`) 정리
이 변경은 유지보수성을 높이고 코드 복잡성을 줄이기 위함입니다.

refactor(assetManagement): SERVICE_SERVER_URL로 API 베이스 경로 통일

---

frontend/next.config.mjs
frontend/src/entities/assetManagement/apis/getAssetsStock.ts
frontend/src/shared/utils/getServiceServerUrl.ts

- API 호출 시 서버 URL을 동적으로 처리하기 위해 `getServiceServerUrl` 유틸 함수를 새로 추가함.
- Next.js의 rewrites 설정에 외부 API 요청을 위한 리라이트 규칙 추가.
- 기존 코드 내 하드코딩된 URL을 `getServiceServerUrl`로 변경하여 유지보수성을 개선함.

feat(api): 서버 URL 동적 처리 및 API 리라이트 추가

---

frontend/next.config.mjs
frontend/src/shared/constants/api.ts

API 서버에서 포트를 지정하지 않도록 URL을 수정했습니다.
- next.config.mjs의 rewrite destination에서 포트 번호(8000) 제거
- constants 파일의 SERVICE_SERVER_URL에서 포트 번호(8000) 제거

fix(config): API URL에서 포트 번호 제거

---

frontend/vercel.json

Vercel 배포에서 특정 API 요청을 외부 API로 전달하기 위한 rewrite 설정을 추가했습니다. 이를 통해 `/api/:path*` 요청이 `https://api.gaemischool.com/api/:path*`로 전달됩니다.

feat(config): Vercel 리다이렉트 설정 추가

---

frontend/src/shared/ui/NumberInput.tsx

- `onBlur` 이벤트에서 변경되지 않은 값이 부모 컴포넌트로 전달되는 문제를 수정했습니다.
- 이제 `localValue`가 기존 `value`와 다를 때만 `onChange`가 호출됩니다.

fix(NumberInput): onBlur 시 불필요한 값 업데이트 방지

---

frontend/src/entities/asset-management/apis/deleteAssetStockParent.ts
frontend/src/entities/asset-management/apis/deleteAssetStockSub.ts

- `SERVICE_SERVER_URL` 대신 `getServiceServerUrl` 사용으로 URL 동적 설정
- `deleteAssetStockParent` 함수의 ID 파라미터를 코드로 변경
- URL 구조를 변경하여 API 호출 방식 개선

refactor(asset-management): delete API URL 및 함수 파라미터 수정

---

frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementSheet.tsx

- `tableData.length`에서 `data.stock_assets`를 기반으로 계산하도록 변경

[#OLF-15] fix(asset-management): 총 건수 계산 로직 수정

---

frontend/src/shared/ui/NumberInput.tsx
frontend/src/stories/NumberInput/NumberInput.stories.tsx

- `value`와 `onChange` prop의 타입을 `string`에서 `number`로 변경하여 일관성을 강화
- `parseNumber` 함수 추가로 입력 값 처리 로직 개선
- 불필요한 유틸 함수 제거 및 외부 라이브러리 함수(`decommaizeNumber`)로 대체
- 관련 스토리북 코드도 새로운 타입에 맞게 수정

refactor(NumberInput): value prop 타입을 string에서 number로 변경

---

frontend/src/features/asset-management/atoms/openedFieldAtom.ts
frontend/src/features/asset-management/index.ts
frontend/src/widgets/asset-management-draggable-table/hooks/useHandleAssetStock.ts
frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementSheet.tsx

- `jotai`를 사용하여 openedFieldAtom 상태 생성 및 적용
- 기존 useState를 jotai atom 기반으로 리팩토링하여 전역 상태 관리로 변경
- openedFields의 관리 방식 변경: 배열 -> Set 객체로 전환해 성능 최적화

feat(asset-management): 서브행 추가시 해당 종목 아코디언 열리는 기능 추가

---

frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementSheet.tsx

- 컴포넌트 최초 마운트 시 `useEffect`를 활용하여 자산 열림 상태를 초기화하도록 로직 추가
- `useRef`를 통해 초기 마운트 여부를 확인하여 중복 실행 방지

feat(ui): 초기 렌더링 시 자산 열림 상태 설정 추가

---

frontend/src/shared/ui/Tooltip.tsx
frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementSheetHeader.tsx

- 툴팁이 필요한 필드를 검사하는 함수 `checkIsTooltipNeed` 추가
- 필드에 따른 툴팁 내용을 반환하는 `getTooltipContent` 구현
- 헤더에서 툴팁 생성 로직을 분리하여 `getTooltipForHeader`로 재사용 가능하도록 수정
- 기존 툴팁 최대 너비 조정 (`max-w-[230px]` 추가)로 UI 개선

feat(ui): [#OLF-36] 툴팁 생성 로직 분리 및 재사용성 강화

---

frontend/src/app/AuthProvider.tsx
frontend/src/app/layout.tsx
frontend/src/entities/user/actions/logout.ts
frontend/src/entities/user/contexts/AuthContext.tsx
frontend/src/entities/user/model/useUserLogout.ts
frontend/src/widgets/header/ui/DropdownMenus.tsx

- 로그아웃 로직에서 불필요한 revalidatePath와 redirect 제거
- `initializeUser`를 react-query 기반으로 변경하여 상태 관리 개선
- `AuthProvider` 및 컨텍스트에서 `logout` 함수 제거
- 로그아웃 성공 시 라우터를 새로고침하도록 수정
- 컴포넌트 계층 구조를 QueryClientProvider -> AuthProvider로 변경

refactor(auth): [#OLF-37] 로그아웃 로직 및 유저 초기화 리팩토링

---

frontend/src/entities/asset-management/types/asset-management.d.ts
frontend/src/widgets/asset-management-draggable-table/ui/AssetManagementSheet.tsx

- Asset 타입에 "매매" 속성을 추가하여 매수/매도 구분 가능
- 매도 상태일 경우 수익률 및 수익금 필드에 비활성화 UI 적용
- 서브 타입 여부를 확인하는 유틸 함수 `isAssetStockSub` 추가

feat(asset-management): "매매" 종류가 매도인 경우 "수익금", "수익률" disabled 처리

---

frontend/src/shared/constants/api.ts

- 개발 환경과 운영 환경에 따라 서로 다른 서버 URL을 사용할 수 있도록 수정
- 개발 환경에서는 `api.gaemischool.com`, 운영 환경에서는 `api.ollass.com`을 사용

feat(constants): 환경별 서버 URL 분리

---

frontend/src/shared/index.ts
frontend/src/shared/ui/Card.tsx
frontend/src/shared/ui/SegmentedButton.tsx
frontend/src/shared/ui/TooltipWithIcon.tsx
frontend/src/widgets/Summary/ui/SummaryCard.tsx
frontend/src/widgets/estimate-dividend/ui/EstimateDividendClient.tsx
frontend/src/widgets/investment-performance-chart/ui/InvestmentPerformanceChartClient.tsx

- TooltipWithIcon 컴포넌트를 생성하여 툴팁 기능 구현
- Card 컴포넌트에 `withTooltip` 및 `tooltipText` props 추가로 툴팁 지원
- SummaryCard 및 주요 헤더에 툴팁 적용하여 정보 제공 강화
- 추정치 및 분석 데이터에 대해 툴팁으로 상세 설명 추가

feat(ui): TooltipWithIcon 컴포넌트 추가 및 카드와 헤더에 툴팁 기능 통합

---

frontend/src/app/AuthProvider.tsx
frontend/src/app/layout.tsx
frontend/src/app/loading.tsx
frontend/src/entities/user/contexts/AuthContext.tsx
frontend/src/widgets/header/ui/DropdownMenus.tsx
frontend/src/widgets/header/ui/Profile.tsx
frontend/src/widgets/join-dialog/ui/JoinDialog.tsx
frontend/src/widgets/join-dialog/ui/NicknameSetup.tsx

- AuthProvider에서 초기 사용자 상태를 props로 전달받도록 변경
- setUser를 AuthContext에서 지원하도록 수정
- Header, DropdownMenu 등 컴포넌트에 사용자 상태와 관련 로직 주입
- 불필요한 initializeUser 제거 및 관련 로직 단순화
- loading 페이지 추가하여 사용자 경험 개선

refactor(Auth): 사용자 상태 관리 및 초기화 로직 개선

---

frontend/src/entities/user/model/useUserLogout.ts
frontend/src/widgets/header/ui/DropdownMenus.tsx

- useRouter 대신 useUser를 사용하여 setUser(null)로 상태 초기화
- DropdownMenus의 조건부 렌더링 로직을 간소화

refactor(user): 로그아웃 로직 및 조건부 렌더링 수정
